FROM mariadb:latest


COPY mboardlogin.sql /docker-entrypoint-initdb.d

ENV MYSQL_ROOT_PASSWORD: root
ENV MYSQL_USER: mboardlogin
ENV MYSQL_PASSWORD: FedUlQ8Hbl5KGxeF
ENV MYSQL_DATABASE: mboardlogin

EXPOSE 3306

